### ISSUE TITLE
how to extract Resnet feature for new dataset?

### ISSUE THREAD

**Issue by chenboheng** [ramakanth-pasunuru/video_captioning_rl#1]
excellent work. However, if I want to use the in a new dataset, how can I extract the resnet feature? Can you give me some hints? Thank you very much.

**Comment by ramakanth-pasunuru** [comment]
ResNet: already available in pytorch (https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py)

ResNeXt: I used this to extract ResNeXt features: (https://github.com/facebookresearch/ResNeXt)
