### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by AmingWu** [ramakanth-pasunuru/video_captioning_rl#4]
There is an error in your code.

video_captioning_rl/models/seq2seq_atten.py

frame_packed = nn.utils.rnn.pack_padded_sequence(frames, flengths, batch_first=True)

ValueError: some of the strides of a given numpy array are negative. This is currently not supported, b
ut will be added in future releases.

**Comment by ramakanth-pasunuru** [comment]
This error occurs with the latest version of the pytorch. This repo doesn't support the lastest version of the pytorch. 

The fix for this issue is discussed in this thread: https://github.com/facebookresearch/InferSent/issues/99
